getgenv().toxicPhrases = {
    "you got clapped",
    "nice one",
    "obviously, im better :p",
    "try harder next time",
    "train a lil more",
    "could of won if you were good",
    "try coping harder",
    "kitzoon was here",
    "may the slap gods slap you from this earth",
    "goofy ahh noob",
    "get gud",
    "badddd",
    "join the el' bozo party",
    "you wish you were me",
    "should quit this game if you play like that",
    "wanna-be tryhard",
    "TRAIN LOL",
    "my grandma plays better then you",
    "literally garbago",
    "9/11 was a tragedy, so is you",
    "if common sense is common, why are you without it",
    "sorry, not sorry",
    "its been a year daddy, I really really miss you - quote from you"
}
